[package]
name = "mp4-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atom_macro = { path = "../atom_macro" }

[lib]
path = "src/lib.rs"
