#[derive(Debug)]
pub struct SeqParameterSetData {
    pub profile_idc: u8,
    pub constraint_set_flags: u8,
    // constraint_set0_flag: u8,
    // constraint_set1_flag: u8,
    // constraint_set2_flag: u8,
    // constraint_set3_flag: u8,
    // constraint_set4_flag: u8,
    // constraint_set5_flag: u8,
    // reserved_zero_2bits: u8,
    pub level_idc: u8,
    pub seq_parameter_set_id: u8,
    pub chroma_format_idc: u8,
    pub separate_colour_plane_flag: u8,
    pub bit_depth_luma_minus8: u8,
    pub bit_depth_chroma_minus8: u8,
    pub qpprime_y_zero_transform_bypass_flag: u8,
    pub seq_scaling_matrix_present_flag: u8,
    pub seq_scaling_list_present_flag: [u8; 12],
    pub scaling_list_4x4: [ScalingList; 6],
    pub scaling_list_8x8: [ScalingList; 6],
    pub log2_max_frame_num_minus4: u8,
    pub pic_order_cnt_type: u8,
    pub log2_max_pic_order_cnt_lsb_minus4: u8,
    pub delta_pic_order_always_zero_flag: u8,
    pub offset_for_non_ref_pic: i32,
    pub offset_for_top_to_bottom_field: i32,
    pub num_ref_frames_in_pic_order_cnt_cycle: u8,
    pub offset_for_ref_frame: [i32; 256],
    pub max_num_ref_frames: u8,
    pub gaps_in_frame_num_value_allowed_flag: u8,
    pub pic_width_in_mbs_minus1: u16,
    pub pic_height_in_map_units_minus1: u16,
    pub frame_mbs_only_flag: u8,
    pub mb_adaptive_frame_field_flag: u8,
    pub direct_8x8_inference_flag: u8,
    pub frame_cropping_flag: u8,
    pub frame_crop_left_offset: u16,
    pub frame_crop_right_offset: u16,
    pub frame_crop_top_offset: u16,
    pub frame_crop_bottom_offset: u16,
    pub vui_parameters_present_flag: u8,
    pub vui: Option<Box<Vui>>,
    // todo: scaling_list
    // todo: vui_parameters
}

#[derive(Debug, Clone)]
pub struct Vui {
    pub aspect_ratio_info_present_flag: u8,
    pub aspect_ratio_idc: u8,
    pub sar_width: u16,
    pub sar_height: u16,
    pub overscan_info_present_flag: u8,
    pub overscan_appropriate_flag: u8,
    pub video_signal_type_present_flag: u8,
    pub video_format: u8,
    pub video_full_range_flag: u8,
    pub colour_description_present_flag: u8,
    pub colour_primaries: u8,
    pub transfer_characteristics: u8,
    pub matrix_coefficients: u8,
    pub chroma_loc_info_present_flag: u8,
    pub chroma_sample_loc_type_top_field: u8,
    pub chroma_sample_loc_type_bottom_field: u8,
    pub timing_info_present_flag: u8,
    pub num_units_in_tick: u32,
    pub time_scale: u32,
    pub fixed_frame_rate_flag: u8,
    pub nal_hrd_parameters_present_flag: u8,
    pub nal_hrd_parameters: Option<Hrd>,
    pub vcl_hrd_parameters_present_flag: u8,
    pub vcl_hrd_parameters: Option<Hrd>,
    pub low_delay_hrd_flag: u8,
    pub pic_struct_present_flag: u8,
    pub bitstream_restriction_flag: u8,
    pub motion_vectors_over_pic_boundaries_flag: u8,
    pub max_bytes_per_pic_denom: u8,
    pub max_bits_per_mb_denom: u8,
    pub log2_max_mv_length_horizontal: u8,
    pub log2_max_mv_length_vertical: u8,
    pub max_num_reorder_frames: u8,
    pub max_dec_frame_buffering: u8,
}

#[derive(Debug, Clone, Copy)]
pub struct ScalingList;
#[derive(Debug, Clone)]
pub struct Hrd {
    pub cpb_cnt_minus1: u8,
    pub bit_rate_scale: u8,
    pub cpb_size_scale: u8,
    pub bit_rate_value_minus1: Vec<u32>,
    pub cpb_size_value_minus1: Vec<u32>,
    pub cbr_flag: Vec<u8>,
    pub initial_cpb_removal_delay_length_minus1: u8,
    pub cpb_removal_delay_length_minus1: u8,
    pub dpb_output_delay_length_minus1: u8,
    pub time_offset_length: u8,
}

#[derive(Debug)]
pub struct SeqParameterSetDataExt {
    pub chroma_format_idc: u32,
    pub separate_colour_plane_flag: u8,
    pub bit_depth_luma_minus8: u32,
    pub bit_depth_chroma_minus8: u32,
    pub qpprime_y_zero_transform_bypass_flag: u8,
    pub seq_scaling_matrix_present_flag: u8,
    pub seq_scaling_list_present_flag: Vec<u8>,
}
